name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir
    services:
      redis:
        image: redis
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Hex
        run: mix local.hex --force
      - name: Rebar
        run: mix local.rebar
      - name: Install Dependencies
        run: mix deps.get --only test
      - name: Test
        run: mix test
